# Generated by Django 3.0 on 2022-03-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220306_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
